### PR TITLE
Build mikktspace using cc instead of cmake

### PR DESCRIPTION
**Pull request by randomPoison**
This PR removes the dependency on CMake in order to build mikktspace. I've replaced the cmake crate with the `cc` crate, which handles all of the work that would be otherwise handled by CMake. The simplicity of the C source code for the library (i.e. a single header and source file pair), and the fact that the C source code isn't subject to a lot of change going forward, means that this crate is a good candidate for using cc instead of CMake.

The advantage of using `cc` over cmake is that it doesn't require developers to have CMake installed on their build machine. Currently, mikktspace will fail to build if CMake is not installed. This PR changes that, such that the library should build so long as the user has any valid C compiler installed (which is required by CMake anyway).

I've tested this on my Windows machine using the MSVC toolchain and confirmed that this works, and I'll address any errors that come up on Mac or Linux in the Travis builds.

Note that this is something of a stopgap measure while waiting for #10. The safest, most portable solution is a pure Rust implementation, but fully converting from C to Rust is a much larger task. In the meantime, switching to `cc` at least allows developers to build mikktspace without installing CMake.

### CODE REVIEW

**Comment by randomPoison** [comment]
Looks like linking is failing on Linux. I'm not sure I understand the errors, though:

```
   Compiling mikktspace v0.1.0 (file:///home/travis/build/gltf-rs/mikktspace)
     Running `rustc --crate-name generate examples/generate.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=0886a47fb5b8de69 -C extra-filename=-0886a47fb5b8de69 --out-dir /home/travis/build/gltf-rs/mikktspace/target/debug/examples -C incremental=/home/travis/build/gltf-rs/mikktspace/target/debug/incremental -L dependency=/home/travis/build/gltf-rs/mikktspace/target/debug/deps --extern cgmath=/home/travis/build/gltf-rs/mikktspace/target/debug/deps/libcgmath-049d111eb7158269.rlib --extern mikktspace=/home/travis/build/gltf-rs/mikktspace/target/debug/deps/libmikktspace-57b2cb25a0e211aa.rlib -L native=/home/travis/build/gltf-rs/mikktspace/target/debug/build/mikktspace-ed17abccbd6c02cb/out`
     Running `rustc --crate-name mikktspace src/lib.rs --emit=dep-info,link -C debuginfo=2 --test -C metadata=7a0dbea207095e8a -C extra-filename=-7a0dbea207095e8a --out-dir /home/travis/build/gltf-rs/mikktspace/target/debug/deps -C incremental=/home/travis/build/gltf-rs/mikktspace/target/debug/incremental -L dependency=/home/travis/build/gltf-rs/mikktspace/target/debug/deps --extern cgmath=/home/travis/build/gltf-rs/mikktspace/target/debug/deps/libcgmath-049d111eb7158269.rlib -L native=/home/travis/build/gltf-rs/mikktspace/target/debug/build/mikktspace-ed17abccbd6c02cb/out -l static=mikktspace -l static=mikktspace`
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/travis/build/gltf-rs/mikktspace/target/debug/deps/mikktspace-7a0dbea207095e8a.1eifmzqw2rmurcug.rcgu.o" "/home/travis/build/gltf-rs/mikktspace/target/debug/deps/mikktspace-7a0dbea207095e8a.1y16o1qfye96o7m0.rcgu.o" "/home/travis/build/gltf-rs/mikktspace/target/debug/deps/mikktspace-7a0dbea207095e8a.3rngp6bm2u2q5z0y.rcgu.o" "/home/travis/build/gltf-rs/mikktspace/target/debug/deps/mikktspace-7a0dbea207095e8a.4oc10dk278mpk1vy.rcgu.o" "/home/travis/build/gltf-rs/mikktspace/target/debug/deps/mikktspace-7a0dbea207095e8a.oa3rad818d8sgn4.rcgu.o" "-o" "/home/travis/build/gltf-rs/mikktspace/target/debug/deps/mikktspace-7a0dbea207095e8a" "/home/travis/build/gltf-rs/mikktspace/target/debug/deps/mikktspace-7a0dbea207095e8a.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/home/travis/build/gltf-rs/mikktspace/target/debug/deps" "-L" "/home/travis/build/gltf-rs/mikktspace/target/debug/build/mikktspace-ed17abccbd6c02cb/out" "-L" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-l" "mikktspace" "-Wl,--no-whole-archive" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-019326da6686230a.rlib" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-7f8a78dfff7bac57.rlib" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-dbfbcb47517df890.rlib" "-Wl,--start-group" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-0888da25bc5aa659.rlib" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-c21a3f7e9b2ce71d.rlib" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-a89ec74248f6f925.rlib" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-9232e45013d81e94.rlib" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-afbe0a28ca4ea99f.rlib" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-bcf95ff3aa4e3276.rlib" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-26716181a02171e3.rlib" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-978afee7e21437ec.rlib" "-Wl,--end-group" "/home/travis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-3f4ad009a7cf735f.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: /home/travis/build/gltf-rs/mikktspace/target/debug/build/mikktspace-ed17abccbd6c02cb/out/libmikktspace.a(mikktspace.o): In function `genTangSpaceDefault':
          /home/travis/build/gltf-rs/mikktspace/libmikktspace/mikktspace.c:225: multiple definition of `genTangSpaceDefault'
          /home/travis/build/gltf-rs/mikktspace/target/debug/build/mikktspace-ed17abccbd6c02cb/out/libmikktspace.a(mikktspace.o):/home/travis/build/gltf-rs/mikktspace/libmikktspace/mikktspace.c:225: first defined here
          /home/travis/build/gltf-rs/mikktspace/target/debug/build/mikktspace-ed17abccbd6c02cb/out/libmikktspace.a(mikktspace.o): In function `genTangSpace':
          /home/travis/build/gltf-rs/mikktspace/libmikktspace/mikktspace.c:230: multiple definition of `genTangSpace'
          /home/travis/build/gltf-rs/mikktspace/target/debug/build/mikktspace-ed17abccbd6c02cb/out/libmikktspace.a(mikktspace.o):/home/travis/build/gltf-rs/mikktspace/libmikktspace/mikktspace.c:230: first defined here
          collect2: error: ld returned 1 exit status
```

The linker is complaining that there are multiple definitions for `genTangSpaceDefault` and `genTangSpace`. Looking at the source code, though, there's no way that the C source is generating those symbols multiple times (which could be the case e.g. if preprocessor defines were setup incorrectly). I'm guessing the generated `libmikktspace` library is being linked in multiple times, but I don't see how that would happen?

**Comment by randomPoison** [comment]
Oh wait, it's right there: `-l static=mikktspace -l static=mikktspace`

I'll bet that `cc` already handles doing `println!("cargo:rustc-link-lib=static=mikktspace");` and we can remove it from `build.rs`.

**Review by alteous — CHANGES_REQUESTED** [review]
Thanks for the PR. This direction makes sense given how small this library is.

I think `mikktspace.c` is listed twice on line 6 of build.rs, which is probably causing the 'multiple definition' errors. Interestingly, the build succeeds on some nightly and beta targets.

**Comment by randomPoison** [comment]
🙌 Great catch! It would have taken me forever to notice that.

**Comment by randomPoison** [comment]
@alteous Looks like this is fixed up! Travis is passing and I can confirm that it builds on my Windows machine 😃

**Review by bwasty — APPROVED** [review]

**Comment by alteous** [comment]
Thank you!

**Comment by randomPoison** [comment]
@alteous Would it be possible to release a 0.1.1 version of mikktspace that includes this change? Currently I can manually patch in the updated version if I use a crate that depends on mikktspace, but if this were released as 0.1.1 then cargo could automatically pull in the new version.

**Comment by alteous** [comment]
Version 0.1.1 has been published.

**Pull request merged**
